### ISSUE TITLE
How to pass values to set_pixel?

### ISSUE THREAD

**Issue by tolnai** [cgomesu/rpi-sensehat-mqtt#6]
I've been struggling with this a while, and need some help. What should be the mqtt payload for calling set_pixel? The signature if set_pixel is `def set_pixel(self, x, y, *args):` ([taken from here](https://github.com/astro-pi/python-sense-hat/blob/v2.4.0/sense_hat/sense_hat.py)), so I can't pass in "pixel" or "r", "g" and "b" arguments via the **kwargs method. I tried "args" and "*args", "arg_0" ad various other formats, none of them worked, I always get this error: set_pixel() got an unexpected keyword argument "[arg name from above]".
There is no example in the repo for this, so can you please help? Thanks!

**Comment by cgomesu** [comment]
> none of them worked

can you provide an **example of payload**?

the portion of the code that is relevant to you is the following:

https://github.com/cgomesu/rpi-sensehat-mqtt/blob/2b38005d19558443f2be0f1039c8260eb4c7d8a9/rpi_sensehat_mqtt.py#L58-L78

in short, it assumes you are passing `key`:`arg` (kwarg) structure when it mentions `f_kwargs`, as in a dictionary data structure. so, a method, such as `set_pixel()` must define named parameters for this to work. according to the code you mentioned, [it does](https://github.com/astro-pi/python-sense-hat/blob/c5b81c6a34163deb572fd76102a615b7cdc107bb/sense_hat/sense_hat.py#L345-L381)--namely, `x` and `y`. the problem is how `pixels` is implemented there. it assumes that they are expanded by `args` (e.g., tuple or list-like structure) that gives the RGB or an iterable that contains them, _but such parameter is not named in the signature of the method_, and therefore, the line

```python
elif f=='set_pixel': sense_led.sense.set_pixel(**f_kwargs)
```

won't work. A simple fix is to edit it to parse as `*args` instead (unnamed expansion) and in your payload, you send an iterable with the parameter values:

```python
elif f=='set_pixel': sense_led.sense.set_pixel(*f_kwargs)
```
```json
{
    "set_pixel" : "[x,y,r,g,b]"
}
```

if that doesn't work, then you might need to do a bit of preprocessing on the payload. say, pass a string with a comma separating the parameters and then do the following:


```python
elif f=='set_pixel': sense_led.sense.set_pixel(*f_kwargs.split(','))
```
```json
{
    "set_pixel" : "x,y,r,g,b"
}
```

that's my intuition right now. it's been a while since I last touched this code... anyway, give it a try, play around with it, and let me know if it doesn't work.

**Comment by cgomesu** [comment]
for my own future reference:

>```python
>elif f=='set_pixel': sense_led.sense.set_pixel(*f_kwargs.split(','))
>```

this actually might be strategy for sending and parsing payloads.

**Comment by tolnai** [comment]
Thanks for the quick feedback. I was trying payloads like `{ "set_pixel" : { "x": 0, "y": 0, "args": [255, 255, 255] } }` or `{ "set_pixel" : { "x": 0, "y": 0, "pixel": [255, 255, 255] } }`, but since *args is not named, they didn't work - just as you said. Due to the signature of set_pixel I guess we just can't mixed named and non-named vars.

I tried to do some magic with having a special "args" in kwargs, popping it and passing then both kwargs and args into set_pixel but it was not working, so just simply edited toe code to:
```
elif f=='set_pixel': sense_led.sense.set_pixel(*f_kwargs)
```
And then using the payload `{ "set_pixel" : [0, 0, 255, 255, 255] }` works fine.

**Comment by tolnai** [comment]
If I may ask for some more improvement, now I can send multiple commands, but only different commands. That is not that useful (flipping and setting a pixel?) - I guess most use cases are either just show a text/image, or setting 1 or more pixels. This latter is not possible at the moment, it needs separate mqtt messages. I don't mind, will handle it with node-red, but it's a suggestion.
Also, it would be awesome if this module would handle some timing transparently (like fading or blinking), which is difficult todo externally (what if some messages get lost, the case of clearing a blinking pixel means stopping a blinking cycle, etc.). But I know this is really just a wrapper for the sensehat library. :)

**Comment by cgomesu** [comment]
> But I know this is really just a wrapper for the sensehat library

exactly. the enhancements you mentioned are sensible ones and there are other things I want to improve in the current implementation (one of the threads use way too much cpu time and I'm not sure why). however, my hands are full at the moment (and will likely continue to be until the end of the year).

if you don't mind, please open a new issue for each of such enhancement requests and I'll try to take a closer look at them when I have a bit of free time. also, feel free to make the changes yourself and submit a PR to add them here. help is always welcomed!
